### PR TITLE
Update adminhtml/config

### PR DESCRIPTION
**Pull request by justinbeaty**
See discussion https://github.com/OpenMage/magento-lts/pull/2945

### CODE REVIEW

**Comment by sreichel** [comment]
Maybe add typehints for `$inputType` parametes?

**Comment by justinbeaty** [comment]
Done

**Comment by sreichel** [comment]
Last one? `$helper = Mage::helper('adminhtml/config');` can be called outside `foreach` loop.

**Comment by fballiano** [comment]
@sreichel I moved the $helper call outside the foreach right after merging ;-)

**Comment by fballiano** [comment]
thanks to both of you :-)

**Pull request merged**
